### ISSUE TITLE
[enchancement] Activation by keyboard shortcut

### ISSUE THREAD

**Issue by DDzwiedziu** [mikl/browser-go-to-random-tab#3]
Yep, that's it, just a suggestion

**Comment by panstav** [comment]
chrome://extensions/shortcuts

**Comment by DDzwiedziu** [comment]
Does not work for Firefox.

**Comment by panstav** [comment]
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by mikl** [comment]
Good idea. This was implemented in #2, and is part of the latest version of the extension on AMO.
